CREATE TABLE [dbo].[Agent]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[UserId] nvarchar(128),
	[UserName] nvarchar(max),
    [FisrtName] nvarchar(max),
	[LastName] nvarchar(max),
	[Contact1] nvarchar(max),
	[Contact2] nvarchar(max),
	[Address] nvarchar(max),
	[Designation] int,
	[DepartmentId] int,
	[PositionName] nvarchar(max),
	[JobDescription] nvarchar(max),
	[ShiftId] int not null default(1),
	[Email] nvarchar(max),
	[ImageUrl] nvarchar(max),
	[IsActive] bit,
	[SuperVisorId] int,
	[IsSupervisor] bit,
	[HasSupervisor] bit,
	[CreatedBy] nvarchar(max),
	[CreatedAt] DateTime,
	[UpdatedBy] nvarchar(max),
	[UpdatedAt] DateTime,
	[Date] Datetime,
	[DeductionInDays] INT NOT NULL DEFAULT 0, 
    [ConsecutiveLateCounter] INT NOT NULL DEFAULT 0, 
    [RemainingLeaves] INT NOT NULL DEFAULT 30,
	[AnnualLeaves] INT NOT NULL DEFAULT 20,
	[MedicalLeaves] INT NOT NULL DEFAULT 10,
	[FirstInterviewBy] nvarchar(max),
	[SecondInterviewBy] nvarchar(max),
	[ApprovedBy] nvarchar(max),
	[Remarks] nvarchar(max),
	[Gender] nvarchar(max),
	[Salary] decimal(18,3) not null default(0),
	[ApprovalImageUrl] nvarchar(max),
	[DocumentsImageUrl] nvarchar(max),
	[CompanyBelonging] nvarchar(max),
	[ExitEmployeeFormImageUrl] nvarchar(max),
	[HouseRentAllowance] decimal(18,3) not null default(0),
	[Utility]decimal(18,3) not null default(0),
	[VehicleAllowance] decimal(18,3) not null default(0),
	[FuelAllowance] decimal(18,3) not null default(0),
	[EOBIDeduction] decimal(18,3) not null default(0),
	[LoanDeduction] decimal(18,3) not null default(0),
	[OtherDeduction] decimal(18,3) not null default(0),
	[OtherDeductionDesc] nvarchar(max),
	[EmpCode] nvarchar(10),
	[Location] nvarchar(20),
	[Section] nvarchar(29),
	[Grade] nvarchar(20),
	[DateOfJoining] Datetime,
	[WWID] nvarchar(max),
	[EmployementType] nvarchar(max),
	[PaidBy] nvarchar(200),
	[CNIC] nvarchar(200),
    Constraint [FK_Agent_User] foreign key ([UserId]) References [dbo].[AspNetUsers] ([Id]),
	Constraint [FK_Agent_Agent] foreign key ([SuperVisorId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_Agent_Shifts] foreign key ([ShiftId]) References [dbo].[Shifts] ([Id])
	--Constraint [FK_Agent_Department] foreign key ([DepartmentId]) References [dbo].[Department] ([Id])
)
