//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentAttendance
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public bool IsPresent { get; set; }
        public bool IsLate { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool IsExcused { get; set; }
        public bool Status { get; set; }
        public string Remarks { get; set; }
        public bool IsAttendanceMarked { get; set; }
        public bool IsAbsent { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int Type { get; set; }
        public int ShiftId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Shifts Shifts { get; set; }
    }
}
