//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentIncentives
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int IncentiveId { get; set; }
        public string AgentName { get; set; }
        public string IncentiveName { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Incentives Incentives { get; set; }
    }
}
