//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public string DocumentUrl { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Agent Agent1 { get; set; }
    }
}
