//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holidays
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Remarks { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
    }
}
