//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDates
    {
        public int Id { get; set; }
        public int LeaveId { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
    
        public virtual Leaves Leaves { get; set; }
    }
}
