//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int Id { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string PaySlipUrl { get; set; }
        public Nullable<System.DateTime> GeneratedOn { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
