//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlip
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PadiBy { get; set; }
        public int DaysWorked { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public int AgentId { get; set; }
        public string Location { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Designation { get; set; }
        public string Section { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string CNIC { get; set; }
        public string Shift { get; set; }
        public string WWID { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> Utility { get; set; }
        public Nullable<decimal> FuelAllowance { get; set; }
        public Nullable<decimal> VehicleAllowance { get; set; }
        public Nullable<decimal> Incentive { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> EOBI { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public string Status { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Department Department { get; set; }
    }
}
