CREATE TABLE [dbo].[PaySlip]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[Date] DateTime,
	[PadiBy] nvarchar(200),
	[DaysWorked] int not null default(30),
	EmpCode nvarchar(100),
	EmpName nvarchar(max),
	AgentId int not null,
	[Location] nvarchar(max),
	[DepartmentId] int ,
	Designation nvarchar(200),
	Section nvarchar(200),
	Grade nvarchar(200),
	DOJ DateTime,
	CNIC nvarchar(200),
	[Shift] nvarchar(200),
	WWID nvarchar(200),
	BasicPay decimal(18,3),
	HouseRent decimal(18,3),
	Utility decimal(18,3),
	FuelAllowance decimal(18,3),
	VehicleAllowance decimal(18,3),
	Incentive decimal(18,3),
	Tax decimal(18,3),
	EOBI decimal(18,3),
	GrossPay decimal (18,3),
	NetPay decimal(18,3),
	[Status] nvarchar(200),
	Constraint [FK_PaySlip_Department] foreign key ([DepartmentId]) References [dbo].[Department] ([Id]),
	Constraint [FK_PaySlip_Agent] foreign key ([AgentId]) References [dbo].[Agent] ([Id])
)
